version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/skip_stop_container.sh
      timeout: 5
      runas: root
